global:
  trace:
    verbose: true

multiplexer:
  collectors:
    - name: tap
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000

  loggers:
    - name: web
      webserver:
        listen-ip: 0.0.0.0
        listen-port: 8080

  routes:
    - src: [tap]
      dst: [web]
